- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hr
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-inspector
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    pocket1: BookSpaceLaws
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraWhite # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
