- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 #1 hr
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 54000 #15 hrs
      inverted: true # stop playing intern if you're good at engineering!
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: true
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorYellow
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraWhite # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtColorYellow
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
