- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance

- type: startingGear
  id: LibrarianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpackLibrarianFilled
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
    pocket2: HandLabeler # for making named bestsellers
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraWhite # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackSatchelLibrarianFilled
  duffelbag: ClothingBackpackDuffelLibrarianFilled
