[game]
hostname = "Ataraxia 🌌"
maxplayers = 70
soft_max_players = 60
desc="""📣 Ataraxia на базе Goob!"""
map_pool="DefaultMapPool"
lobbyenabled = true

# IPIntel stuff
ipintel_enabled = true
ipintel_contact_email = "backmen@bk.ru"

[infolinks]
#website="https://backmen.ru"
discord="https://discord.gg/4Thsjv6QsX"
#wiki="http://wiki.backmen.ru"
github="https://github.com/AtaraxiaSpaceFoundation/Orion-Station-14"
#appeal="https://backmen.ru/tag/ticket"
#patreon="https://boosty.to/backmen"

[physics]
target_minimum_tickrate = 30
timetosleep = 0.1
angsleeptol = 0.01
linsleeptol = 0.001

[update]
restart_delay = 120

[ahelp]
admin_prefix = true
admin_prefix_webhook = true

[afk]
time = 9999999.0
#time=1200.0

[admin]
announce_login = false
announce_logout = false
see_own_notes = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2

[adminlogs]
server_name="ataraxia"

[net]
max_connections = 1024
log_late_msg=false
# Automatic port forwarding!
# Disabled by default because you may not want to do this.
# upnp = true
sendbuffersize=2471071
#receivebuffersize=1471071
lidgren_log_warning = false
lidgren_log_error = false

[netres]
limit = 2.0

[vote]
restart_required_ratio = 0.6
timermap = 60

[hub]
advertise = true
tags = "lang:ru,rp:low,region:eu_e"
