- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 18000
    - !type:OverallPlaytimeRequirement
      time: 108000
  weight: 10
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  arrivalNotificationPrototype: ResearchDirectorArrivalNotification
  supervisors: job-supervisors-captain
  whitelistedSpecies:
    - Human
    - Felinid
  canBeAntag: true
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    id: RnDPDA
    ears: ClothingHeadsetAltScience
