# Jumpsuit
- type: loadout
  id: HeadOfSecurityCommandJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCommandHeadOfSecurity

# Neck
- type: loadout
  id: HeadOfSecurityRoyalCloak
  equipment:
    neck: ClothingNeckCloakRoyalHeadOfSecurity
